spring.application.name=school
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=myUser
spring.datasource.password=1234
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

path.to.avatars.folder=avatars